---
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: monitoring
  labels:
    task: logging
    k8s-app: logstash
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/pipeline
  pipelines.yml: |
    - pipeline.id: TCP-RAW-FILEBEAT
      path.config: "/usr/share/logstash/pipeline/TCP-RAW-FILEBEAT.conf"
      pipeline.workers: 2
      pipeline.output.workers: 2
      pipeline.batch.size: 1000
      pipeline.batch.delay: 500
      config.test_and_exit: true
    - pipeline.id: TCP-RAW-PROMETHEUS
      path.config: "/usr/share/logstash/pipeline/TCP-RAW-PROMETHEUS.conf"
      pipeline.workers: 2
      pipeline.output.workers: 2
      pipeline.batch.size: 1000
      pipeline.batch.delay: 500
      config.test_and_exit: true
  TCP-RAW-FILEBEAT.conf: |-
   input {
     kafka {
     bootstrap_servers => "bootstrap.monitoring:9092"
     topics_pattern => "TCP-RAW-FILEBEAT"
     type => "tcp-raw-filebeat"
     group_id => "logstash-filebeat"
     client_id => "filebeat"
     consumer_threads => 3
     }
   }
   output {
     elasticsearch {
       hosts => ["elasticsearch:9200"]
       manage_template => false
       index => "%{[type]}-%{+YYYY.MM.dd}"
     }
   }
  TCP-RAW-PROMETHEUS.conf: |-
   input {
     kafka {
     bootstrap_servers => "bootstrap.monitoring:9092"
     topics_pattern => "TCP-RAW-PROMETHEUS"
     type => "tcp-raw-prometheus"
     group_id => "logstash-prometheus"
     client_id => "prometheus"
     consumer_threads => 3
     }
   }
   filter {
     json { 
       source => "message"
      }
      json { 
        source => "data"
        target => "data"
      }
   }
   output {
     elasticsearch {
       hosts => ["elasticsearch:9200"]
       manage_template => true
       index => "%{[type]}-%{+YYYY.MM.dd}"
     }
   }