apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    k8s-app: logstash
    task: logging
  name: logging-logstash
  namespace: monitoring
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      k8s-app: logstash
      task: logging
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: logstash
        task: logging
    spec:
      containers:
      - image: docker.elastic.co/logstash/logstash:7.5.0
        imagePullPolicy: Always
        name: logstash
        resources:
          limits:
            memory: 2Gi
          requests: 
            memory: 2Gi
        env:
          - name: LS_JAVA_OPTS
            value: "-Xms1g
                    -Xmx1g
                    -XX:ParallelGCThreads=5
                    -XX:ConcGCThreads=2
                    -XX:+UseConcMarkSweepGC
                    -XX:+UseCMSInitiatingOccupancyOnly
                    -XX:CMSInitiatingOccupancyFraction=85
                    -XX:+AlwaysPreTouch
                    -XX:-OmitStackTraceInFastThrow
                    -XX:+HeapDumpOnOutOfMemoryError
                    -Dcom.sun.management.jmxremote
                    -Dcom.sun.management.jmxremote.authenticate=false
                    -Dcom.sun.management.jmxremote.ssl=false
                    -Dcom.sun.management.jmxremote.local.only=false
                    -Dcom.sun.management.jmxremote.port=1099
                    -Dcom.sun.management.jmxremote.rmi.port=1099
                    -Djava.rmi.server.hostname=127.0.0.1"
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/logstash/config
          name: config
        - mountPath: /usr/share/logstash/pipeline
          name: pipeline
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        fsGroup: 101
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: logstash.yml
            path: logstash.yml
          - key: pipelines.yml
            path: pipelines.yml
          name: logstash-config
        name: config
      - configMap:
          defaultMode: 420
          items:
          - key: TCP-RAW-FILEBEAT.conf
            path: TCP-RAW-FILEBEAT.conf
          - key: TCP-RAW-PROMETHEUS.conf
            path: TCP-RAW-PROMETHEUS.conf
          name: logstash-config
        name: pipeline
status: {}
